apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: restapi-hpa
  labels:
    name: restapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: restapi-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50