apiVersion: v1
kind: Service
metadata:
  name: restapi-svc
  labels:
    name: restapi-svc
    app: Mentorship
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30004
  selector:
    name: restapi-pod
    app: Mentorship
