apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    name: mongo-svc
    app: Mentorship
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongodb
    app: Mentorship
