apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: Mentorship
spec:
  containers:
  - name: mongodb
    image: mongo
    ports:
    - containerPort: 27017
    env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "odynz"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "0X1A&^%adsadadas3242"